### ISSUE TITLE
Missing raz configuration from variables.tf

### ISSUE THREAD

**Issue by Avanish268** [cloudera-labs/cdp-tf-quickstarts#38]
Hi Team,

Can we add below raz configuration block to our variables.tf file? This way user will have control on whether to enable or disable raz authorization. Similar to what we have here.
Reference: https://github.com/cloudera-labs/terraform-cdp-modules/commit/eb06774b5e286e7f524610eb9dc8375e5defa9f4

variable "enable_raz" {
   type = bool

  description = "Flag to enable Ranger Authorization Service (RAZ)"

   default = true
 }

File location: https://github.com/cloudera-labs/cdp-tf-quickstarts/blob/main/aws/variables.tf

**Comment by jimright** [comment]
Hi @Avanish268,

We added the `enable_raz` input to each of the quickstarts as part of PR#41.

Many thanks for the suggestions.
